version: '3.1'

services:
  app:
    entrypoint: [bin/start]
    image: afarhat/bbb-demo
    container_name: bbb-demo
    env_file: .env
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./log:/usr/src/app/log

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
